#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;

namespace Supermarkets.Task1.MySql	
{
    public partial class Vendor
    {
        public virtual int ID { get; set; }
		
        public virtual string Name { get; set; }
		
        private IList<Product> _products = new List<Product>();

        public virtual IList<Product> Products
        {
            get
            {
                return this._products;
            }
        }
    }
}
#pragma warning restore 1591