#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace Supermarkets.Task1.MySql	
{
    public partial class Product
    {
        public virtual int ID { get; set; }
		
        public virtual int VendorID { get; set; }
		
        public virtual string Name { get; set; }
		
        public virtual int MeasureID { get; set; }
		
        public virtual decimal BasePrice { get; set; }
		
        public virtual Vendor Vendor { get; set; }
		
        public virtual Measure Measure { get; set; }
    }
}
#pragma warning restore 1591